global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "app"
    metrics_path: /metrics
    static_configs:
      - targets: ["app-alb-326837333.eu-central-1.elb.amazonaws.com:80"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]