apiVersion: v1
kind: Secret
metadata:
  name: hrm-secrets
type: Opaque
stringData:
  OKTA_DOMAIN: "https://integrator-1195306-admin.okta.com"
  OKTA_API_TOKEN: "00SaxtpULiNnDEuyGLAX_NHOCopprJZ-ad2VWvxLdI"
  SECRET_KEY: "yordan-123"
  DATABASE_HOST: "db"
  DATABASE_PORT: "3306"
  DATABASE_NAME: "hrm_db"
  DATABASE_USER: "hrm_user"
  DATABASE_PASSWORD: "hrm_password"
