apiVersion: v1
kind: Service
metadata:
  name: hrm-service
  namespace: hrm-test
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  type: LoadBalancer
  selector:
    app: hrm-web
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
