apiVersion: v1
kind: Service
metadata:
  name: hrm-service
  namespace: hrm-test
  labels:
    app: hrm-web
spec:
  selector:
    app: hrm-web
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: ClusterIP

